// Error handling
let a = 1;
let b = 2;
console.log(a);
console.log(b);

try{
    console.log(a+c);
}
catch(e){
    console.log(e);
}